"""Mixins for gui.py."""

from __future__ import annotations

from .actions import ActionsMixin
from .annotation_display import AnnotationDisplayMixin
from .app_shell import AppShellMixin
from .brush_tools import BrushToolsMixin
from .canvas_context_menu import CanvasContextMenuMixin
from .canvas_drawing import CanvasDrawingMixin
from .canvas_events import CanvasEventsMixin
from .canvas_hover import CanvasHoverMixin
from .canvas_right_image import CanvasRightImageMixin
from .canvas_selection import CanvasSelectionMixin
from .canvas_tool import CanvasToolMixin
from .cca_edits import CcaFrameEditResultMixin
from .cca_workflows import CcaWorkflowMixin
from .cell_cycle import CellCycleMixin
from .combine import CombineMixin
from .curvature_tools import CurvatureToolsMixin
from .custom_annotations import CustomAnnotationsMixin
from .data_loading import DataLoadingMixin
from .deleted_rois import DeletedRoisMixin
from .display_decorations import DisplayDecorationsMixin
from .draw_clear_region import DrawClearRegionMixin
from .edit_id import EditIdMixin
from .exporting import ExportingMixin
from .formatting import FormattingMixin
from .frame_metadata import FrameMetadataMixin
from .frame_navigation import FrameNavigationMixin
from .geometry import GeometryMixin
from .graphics import GraphicsMixin
from .image_controls import ImageControlsMixin
from .image_display import ImageDisplayMixin
from .label_edits import LabelEditMixin
from .label_editing import LabelEditingMixin
from .label_roi import LabelRoiMixin
from .label_transform_tools import LabelTransformToolsMixin
from .layout_controls import LayoutControlsMixin
from .lineage_interactions import LineageInteractionsMixin
from .lineage import LineageMixin
from .magic_prompts import MagicPromptsMixin
from .main import MainGuiMixin
from .main_menu import MainMenuMixin
from .main_toolbar import MainToolbarMixin
from .measurements import MeasurementsMixin
from .mode_controls import ModeControlsMixin
from .model_registry import ModelRegistryMixin
from .object_cleanup import ObjectCleanupMixin
from .object_counts import ObjectCountMixin
from .object_properties import ObjectPropertiesMixin
from .object_search import ObjectSearchMixin
from .points_layers import PointsLayersMixin
from .points import PointsMixin
from .preprocessing import PreprocessingMixin
from .quick_settings import QuickSettingsMixin
from .saving import SavingMixin
from .seg_for_lost_ids import SegForLostIdsMixin
from .segmentation import SegmentationMixin
from .session import SessionMixin
from .status_hover import StatusHoverMixin
from .tables import TableMixin
from .tool_activation import ToolActivationMixin
from .tracking import TrackingMixin
from .undo_redo import UndoRedoMixin
from .whitelist import WhitelistMixin
from .window_events import WindowEventsMixin
from .worker import WorkerMixin
from .workspace import WorkspaceMixin
