# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
version = '1.2.4rc4.dev12+gab1f4ee.d20220307'
version_tuple = (1, 2, 4, 'dev12', 'gab1f4ee.d20220307')
