name: Report a bug
description: Report an error, problem or unexpected behavior in Cell-ACDC.
title: "<Comprehensive title summarizing the bug>"
labels: [":bug: Bug"]

body:
  - type: markdown
    attributes:
      value: >
        Thank you for reporting an issue!
        Please, **remember to upload the log file**. You can find the log file from the 
        menu `Help --> Show log files...`

  - type: textarea
    validations:
      required: true
    attributes:
      label: "Description:"
      description: >
        Describe your issue with all necessary detail.
        What kind of behavior are you experiencing?
        What would you expect instead?
        Upload the log file here too. You can find the log file from the 
        menu on the top menubar called `Help --> Show log files...`
      placeholder: |
        Your description...

  - type: textarea
    attributes:
      label: "Way to reproduce:"
      description: >
        Provide a as many details as possible about the process required to 
        reproduce the error.

  - type: textarea
    attributes:
      label: "(Optional) Link to data to reproduce error:"
      description: >
        Many issues are specifically related to the data you are using. If possible, 
        consider providing a link to download the data that I can test with. 
        You could use Google Drive and share it with me at padovaf@tcd.ie

  - type: textarea
    attributes:
      label: "Terminal output:"
      description: >
        Paste here the entire terminal session.
      placeholder: |
        Full error or terminal output..
      render: Shell
    
  - type: input
    attributes:
      label: "Log file:"
      description: You can find the log files from the menu `Help --> Show log files...` 
      placeholder: |
        Drag and drop here the relevant log file...

  - type: textarea
    attributes:
      label: "Version information:"
      description: |
        After activating the environment where you have Cell-ACDC installed, 
        run the following command and paste the output
        ```shell
        acdc -v
        ```
      placeholder: |
        Version information...
      render: Shell